name: Cerberus
version: '${project.version}'
main: lzxus.cerberus.Cerberus
api-version: 1.18
authors: [ lzxus ]
description: A plugin with endless capabilities. Maybe.
commands:
  ce:
    description: Type /ce to view the Cerberus Menu.
    usage: /ce
    permission: cerberus.main
    aliases: [cerberus, cerb]
  cdebug:
    description: Displays all plugin data for local player.
    usage: /cdebug
    permission: cerberus.debug
  cclean:
    description: Cleans world of all wolves. Only for OPed members.
    usage: /cclean
    permission: cerberus.clean

