name: Cerberus
version: '${project.version}'
main: lzxus.cerberus.Cerberus
api-version: 1.18
authors: [ lzxus ]
description: A plugin with endless capabilities. Maybe.
commands:
  ce:
    description: Type /ce or /ce help to view the Cerberus Menu.
    usage: /ce, /ce help
    permission: cerberus.main
  ce debug:
    description: Displays all plugin data for local player.
    usage: /ce debug
    permission: cerberus.debug
  ce clean:
    description: Cleans world of all wolves. Only for OPed members.
    usage: /ce clean
    permission: cerberus.clean

